name: Deploy Model Update

on:
  pull_request:
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Build Docker image
      - name: Build Docker image
        run: docker build -t your_docker_image_name .

      # Tag Docker image
      - name: Tag Docker image
        run: docker tag your_docker_image_name your_docker_repository:latest

      # Push Docker image to Docker registry
      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your_docker_repository:latest
