artifact_location: file:///Users/sarahlenet/Desktop/IntroMLOPS/mlflow
creation_time: 1713861237199
experiment_id: '535770460607192603'
last_update_time: 1713861246276
lifecycle_stage: deleted
name: experiment
tags: {}
