artifact_location: /Users/sarahlenet/Desktop/IntroMLOPS/mlflow
creation_time: 1713861261990
experiment_id: '566282441616450182'
last_update_time: 1713861328406
lifecycle_stage: deleted
name: experiments
tags: {}
