artifact_location: /Users/sarahlenet/Desktop/IntroMLOPS/mlflow/other_experiment/
creation_time: 1713861281629
experiment_id: '416726008623564502'
last_update_time: 1713861326131
lifecycle_stage: deleted
name: experiment2
tags: {}
